[package]
name = "ml-prefetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[dev-dependencies]
criterion = "0.5"
rand = "0.8.5"

[[bench]]
name = "prefetcher_benchmark"
harness = false